### ISSUE TITLE
Terminal not printing anything

### ISSUE THREAD

**Issue by nailuj29** [Limine-Bootloader/Limine#134]
**Limine version used**
2.64

**Expected behavior**
The terminal prints

**Actual (broken) behaviour**
My kernel just shows a blank screen

**To Reproduce**
code can be found at https://github.com/nailuj29gaming/esos

**Additional context**
I'm using the zigvale library to generate the stivale2 header, but I don't think the issue is there

**Comment by Mintsuki** [comment]
I don't know zig, but you don't seem to specify the identifier [here?](https://github.com/nailuj29gaming/esos/blob/main/kernel/src/stivale/tags.zig#L3-L9)

**Comment by RiscInside** [comment]
Could you check if the terminal tag is supplied by limine?

You can do that, for example, by removing `while (true)` hang loop and replacing it with division by 0

**Comment by nailuj29** [comment]
@mintsuki zigvale automatically puts the identifier into the struct. I really don't need the identifier in the framebuffer tag either, but my language server was telling me to include it.

**Comment by Mintsuki** [comment]
Upon further examination (I built the project and tested it) - The issue is caused by the fact that SSE instructions are emitted by the compiler. This is obviously bogus since you need to enable SSE yourself if you want to use it (and usually kernels disable SSE for this, and other reasons).

There is another issue that masked this problem: When running qemu with `-M q35`, instead of crashing/resetting on triple faults, the machine just hangs, masking the issue. Running qemu without that flag, and with `-d int -no-reboot -no-shutdown -M smm=off` quickly revealed the problem.

**Comment by nailuj29** [comment]
Thank you!
