### ISSUE TITLE
Unable to cross-compile for i686 target

### ISSUE THREAD

**Issue by bkauler** [Limine-Bootloader/Limine#198]
I posted about cross-compiling in OpenEmbedded for a x86_64 target, running on a x86_64 host, in #193 
The solution in that case was to put this into the recipe:

`export CROSS_TOOLCHAIN="${TARGET_SYS}"`

I have just completed a build in OpenEmbedded for a i686 target (running on x86_64 host), and out of about 950 packages that compiled successfully before (for x86_64 target), 16 have failed. Nothing vital, except limine has failed, with this message:

```
| checking for i686-poky-linux-gcc... yes
| configure: error: no suitable CROSS_CC found
```
I tried:

`export CROSS_CC="${CC}"`

Because $CC is the cross-compiler. But same fail message.

The thing is, these variable definitions, such as CROSS_TOOLCHAIN, should not be needed. The vast majority of package recipes "just work". This is an example of an autotools build, for Homebank (a personal finance app):

```
# Recipe created by recipetool
# recipetool create -o homebank_5.5.3.bb http://homebank.free.fr/public/homebank-5.5.3.tar.gz

LICENSE = "GPLv2"
LIC_FILES_CHKSUM = "file://COPYING;md5=b234ee4d69f5fce4486a80fdaf4a4263"

SRC_URI = "http://homebank.free.fr/public/homebank-${PV}.tar.gz"
SRC_URI[md5sum] = "8930329b71e5dee78c89db319bf64bef"
SRC_URI[sha256sum] = "073607918a9610087791f36f59e70d1261fee8e4e1146a5cfd5871a1d2d91093"

#2020-09-19 /mnt/sda1/nvme/oe/oe-quirky/build-amd64/tmp/work/core2-64-poky-linux/homebank/5.4.3-r0/temp/run.do_configure.528: line 169: glib-gettextize: command not found. fix: glib-2.0-native
DEPENDS = "libsoup-2.4 gtk+3 libofx glib-2.0 glib-2.0-native intltool-native"

inherit pkgconfig gettext autotools

EXTRA_OECONF = "--with-ofx"

FILES_${PN} += "${datadir}/mime ${datadir}/application-registry ${datadir}/icons ${datadir}/mime-info ${datadir}/appdata"

HOMEPAGE = "http://homebank.free.fr/"
SUMMARY = "Personal finance management"
```

...Homebank has happily compiled for me for aarch6 and i686 targets. For reference, these are variables available in OE:

https://docs.yoctoproject.org/ref-manual/variables.html#term-TARGET_PREFIX

Do you have any thoughts on how to satisfy that "CROSS_CC" requirement?

**Comment by bkauler** [comment]
It is that change of toolchain code in 3.11 that is to blame.
I have just tested compiling 3.10.1, for i686 target, and success. The recipe:

```
# Recipe created by recipetool
# recipetool create -o limine_3.10.1.bb https://github.com/limine-bootloader/limine/releases/download/v3.10.1/limine-3.10.1.tar.gz

SUMMARY = "x86/x86_64 BIOS/UEFI bootloader"
HOMEPAGE = "https://limine-bootloader.org/"

LICENSE = "UCB & GPLv3"
LIC_FILES_CHKSUM = "file://LICENSE.md;md5=566da3e4be60cd868e42cb88c9c0ddd3 \
                    file://stivale/LICENSE.md;md5=21e2e2557201f26b907e5694c9e179b9 \
                    file://libgcc-binaries/COPYING.RUNTIME;md5=fe60d87048567d4fe8c8a0ed2448bcc8 \
                    file://libgcc-binaries/COPYING;md5=64305ff51f34d0aca60d187e21a09d59 \
                    file://libgcc-binaries/COPYING3;md5=d32239bcb673463ab874e80d47fae504 \
                    file://freestanding-headers/LICENSE.md;md5=9621911223dde43748ad798e3804a3ed \
                    file://limine-efi/COPYING;md5=c27a4b4a954b36c8afddf7587fd749be"

SRC_URI = "https://github.com/limine-bootloader/limine/releases/download/v${PV}/limine-${PV}.tar.gz \
           file://remove-ext4-encrypt-warning.patch"

SRC_URI[md5sum] = "f4d5c4219e28b1ddfa7be86609090ae1"
SRC_URI[sha256sum] = "5a2e4cb2cca512b24d697d9714763f6e5ae5c04efbe386487cb4834a86351019"

inherit autotools

DEPENDS = "mtools-native nasm-native coreutils-native"

EXTRA_OECONF = "--enable-all"
```
...just a normal recipe, without having to jump through hoops with special variables.

**Comment by Mintsuki** [comment]
Limine is not a "normal package", it's a multi-architecture supporting bootloader running in freestanding environments.

Its build system is fine, the problem here is that you are passing `--enable-all`, which, if you read the `configure --help`, means that you want to enable all the ports, which includes x86_64 UEFI...

...which is fine, if the compiler *can* target x86_64 *and* i686 as these are the currently supported architectures. i686 GCC toolchains usually only support i686.

So here you have several options:

- You use a native cross compiler like clang, which supports several different architectures and will also be able to build the aarch64 port in the future. This is what I humbly recommend. To do this make sure LLVM and clang are installed as build-time dependencies and pass `TOOLCHAIN=llvm` to `configure`. It should just work. (And native host tools are separate, such as `limine-deploy`, and they build exactly like any other autotools packages, so the `TOOLCHAIN` variable does *not* affect them and they will still (cross-)build with `gcc` or whatever autotools decided based on your settings).

- You *do not* pass `--enable-all` and only selectively enable the i686 ports, so `configure` won't look for a x86_64 capable compiler and build will succeed. This means the x86_64 UEFI port will not be compiled.

- You provide your own x86_64 capable toolchain and 1 by 1 configure and build the i686 and x86_64 ports, with whichever toolchain you want to use. (This is frankly the most awkward solution and I would recommend against it in this context).
