### ISSUE TITLE
Is there any official reasoning on why Terminal Support was deprecated?

### ISSUE THREAD

**Issue by vsczpv** [Limine-Bootloader/Limine#280]
So after a long while I decided to revisit some old project of mine and it used Limine.

I came here to refresh my memory on the protocol only to find a big deprecation warning right below the terminal request feature, followed by a commit made two weeks ago that promptly axed it. Not amused; it was something I used.

I skimmed through the repo but couldn't find anything anywhere saying why it was removed. 

So, why was it removed?

Many thanks, Vinícius.

**Comment by Mintsuki** [comment]
Hi,
Let me start with a premise that the terminal feature of the Limine protocol was only removed in Limine 5.x. Limine 4.x, as of right now, is still supported (i.e. bug fixes and other minor stuff will still be backported to it) and it supports the terminal feature.

The reason it was deprecated and removed in Limine 5.x is that it was hairy and hard to get right for many people, usage wise, due to its many constraints. It was overall a liability, also for the fact that any bug in the Limine terminal could be disastrous if the Limine terminal is running in kernel space, potentially leading to code execution exploits in kernel space.

This has never been reported before, but it could definitely be the case.

The alternative I suggest is to use [Flanterm](https://github.com/mintsuki/flanterm) which is the terminal emulator that Limine uses internally anyways. (Sorry, I know that documentation is lacking, but you can see https://github.com/mintsuki/flanterm-testbench for basic usage).

**Comment by ghost** [comment]
There is a quite new project: https://github.com/ilobilo/limine-terminal
