### ISSUE TITLE
Secure boot violation: Limine boots unsigned kernels

### ISSUE THREAD

**Issue by alicavus** [Limine-Bootloader/Limine#296]
I have dell Vostro machine with Secure Boot in Deployed mode, only signed executables are alowed. I also enrolled MIicrosoft's certficate, so I have dual boot support and no need to sign official Debian kernels.

I have signed my Limine EFI and I can boot without issue.

Today come in my mind to check untrusted kernels and executables. I just grab kernel and initramfs from monthly release of Arch Linux and put them in my disk. It booted from it. I checked other unsigned kernels - they aso are loading without any issue.

**Comment by Mintsuki** [comment]
This is by design. If you want to ensure only approved kernels run, as per PHILOSOPHY.md, you need to add the blake2b checksum to the config file (for any file you want, not just the kernel, also initrd or even a wallpaper file), then use the `limine enroll-config` tool to tell the Limine executable which config file to trust, and *then* you can sign Limine.

**Comment by alicavus** [comment]
I understand the concept with b2sum verification of files.
It seems we allways have to set ```EDITOR_ENABLED``` to ```no``` if we want Secure boot.

**Comment by Mintsuki** [comment]
Yeah, pretty much.

**Comment by Mintsuki** [comment]
I will make it so `EDITOR_ENABLED` will default to `no` if there is a config blake2b enrolled.
