### ISSUE TITLE
Add a way to create an entry for UEFI/BIOS firmware settings 

### ISSUE THREAD

**Issue by janTatesa** [Limine-Bootloader/Limine#299]
Grub and I think that also systemd boot has a feature of giving you an ability to boot into uefi firmware settings. Maybe it also works for bios, not sure because I never had bios. There could be two special boot protocols for uefi and bios. So an entry for UEFI firmware settings could be that 
```
:UEFI firmware settings
    PROTOCOL=uefi
```
I don't know if you can boot uefi differently so other keys would be probably useless. And for bios there could be
```
:BIOS firmware settings
    PROTOCOL=bios
```
Thanks for considering and maybe implementing this feature .

**Comment by WildPenquin** [comment]
I suggest this could be a default feature (a hard-coded keystroke, say F8, S or U) so that a menu item is not needed in the configuration file to reduce clutter. It is always good option to have this feature, firmware settings are available on practically any UEFI-compliant computer, and many bootmanagers already do this (at least ReFind).

It might even be a good idea to scan for common places of EFI executables/tools (such as shells, memory test), but I'm not sure there are any standards for it. In case there isn't, then maybe not, this is not ReFind (there already is the command line which can boot anything). And I'm veering away from this issue report now, sorry! ;-)
