### ISSUE TITLE
Suggestion: document NTFS is supported

### ISSUE THREAD

**Issue by csdvrx** [Limine-Bootloader/Limine#319]
Supporting NTFS along with FAT16/32 is a wonderful idea: a great usecase for NTFS is to have a dedicated partition next to the EFI where .iso images are kept, as they can go beyond the 4G FAT32 limit, and that NTFS partition can be accessed by both Windows and Linux without adding anything extra.

Since you're already supporting NTFS, you may want to document in the README that NTFS is indeed supported: the README only lists as supported: ext2/3/4, FAT12/16/32, ISO9660.

[The pull adding NTFS support was from 2021](https://github.com/limine-bootloader/limine/pull/113), and if I hadn't checked the issues I wouldn't have considered limine for my usecase: to [replace grubfm](https://easy2boot.xyz/agfm/) as a bootmenu to select .isos to boot from, since [grubfm has been dormant since 2022 and was even archived by a1ive last month](https://github.com/a1ive/grub2-filemanager) while [ventoy is still finicky with its check can't go on a normal and well aligned EFI partition](https://github.com/ventoy/Ventoy/issues/1342)

When UKI support is fixed, I think I might even use limine as my main bootloader since it looks very nice. I love the philosophy of keeping it simple, and there's no simple alternative :)

BTW if NTFS support is unstable and you need reliable NTFS tools to test it/fix your NTFS partitions, [you can make a fsck.ntfs using Paragon binaries](https://www.reddit.com/r/archlinux/comments/11qezjd/correctly_checking_ntfs_partitions_dont_use/)

**Comment by Mintsuki** [comment]
> Supporting NTFS along with FAT16/32 is a wonderful idea: a great usecase for NTFS is to have a dedicated partition next to the EFI where .iso images are kept, as they can go beyond the 4G FAT32 limit, and that NTFS partition can be accessed by both Windows and Linux without adding anything extra.

Okay but what would Limine support for NTFS help achieve in that case? You still need a FAT ESP and you can still access a shared NTFS partition from both Linux and Windows without Limine's blessings.

> Since you're already supporting NTFS, you may want to document in the README that NTFS is indeed supported: the README only lists as supported: ext2/3/4, FAT12/16/32, ISO9660.

We are not supporting NTFS. The supported filesystems are those stated in the README. While it is true that NTFS support has been a thing in the past, this was never complete or fully reliable and it was later removed due to this, and because the original author did not intend on maintaining the driver.

> ... I wouldn't have considered limine for my usecase: to replace grubfm as a bootmenu to select .isos to boot from, since grubfm has been dormant since 2022 and was even archived by a1ive last month while ventoy is still finicky with its check can't go on a normal and well aligned EFI partition

Limine is not Ventoy; Limine does not boot .iso files. A lot of people have been spoiled by projects like Ventoy and similar into thinking that booting .iso files is something you "just do", while in reality it involves piling together a bunch of hacks amongst which the injection of kernel modules (for example see how Ventoy boots FreeBSD ISOs).

This will very likely never be supported because it goes well beyond the scope of the Limine project (along with the fact that I personally think there exists no solution for booting .iso files that isn't a gross mess of hacks that needs ad-hoc support for every new OS).
