### ISSUE TITLE
Warning for uninitialized variables

### ISSUE THREAD

**Issue by expnkx** [limine-bootloader/limine#76]
**Limine version used**
Trunk

**Describe the bug**
unlvs@DESKTOP-DFHPDC1 MINGW64 ~/limine
$ make
objcopy -B i8086 -I binary -O default limine.bin limine.o
cc -O2 -pipe -Wall -Wextra -std=c11 limine.o limine-install.c -o limine-install
limine-install.c: In function ‘main’:
limine-install.c:258:14: warning: ‘lb_size’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  258 |         if (!_device_write(BUFFER, LOC, COUNT)) \
      |              ^~~~~~~~~~~~~
limine-install.c:303:14: note: ‘lb_size’ was declared here
  303 |     uint64_t lb_size;
      |              ^~~~~~~

**Comment by mintsuki** [comment]
This issue was supposedly already fixed in https://github.com/limine-bootloader/limine/commit/ddcbfeb4c7524fdc62e44e4173c2c70824c1e208. Are you sure you are running the latest commit from `trunk`? (And are you sure running `trunk` at all is a good idea?)

Other than that this is just a false positive because from the best of my knowledge that variable will never be used uninitialised. Clang also does not report this warning. It seems to be a GCC quirk.
